//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSFilms.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDFilmsAvisContext : DbContext
    {
        public BDFilmsAvisContext()
            : base("name=BDFilmsAvisContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_E_AVIS_AVI> T_E_AVIS_AVI { get; set; }
        public virtual DbSet<T_E_COMPTE_CPT> T_E_COMPTE_CPT { get; set; }
        public virtual DbSet<T_E_FILM_FILM> T_E_FILM_FILM { get; set; }
    }
}
