//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSFilms.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_AVIS_AVI
    {
        public int CPT_ID { get; set; }
        public int FLM_ID { get; set; }
        public System.DateTime AVI_DATE { get; set; }
        public string AVI_TITRE { get; set; }
        public string AVI_DETAIL { get; set; }
        public decimal AVI_NOTE { get; set; }
    
        public virtual T_E_COMPTE_CPT Compte { get; set; }
        public virtual T_E_FILM_FILM Film { get; set; }
    }
}
